#!/bin/bash

while getopts "hd:up" opt; do
    case $opt in
        h)
            echo "entrez-link"
            echo "  -d STR to database name"
            exit 0 ;;
        d)
            dbto=$OPTARG
            if [[ "$dbto" =~ ' ' ]];then
                echo "database must be a single word" > /dev/stderr
                exit 1
            fi
            ;;
        u)
            idmap=1 ;;
        p)
            parse=1 ;;
    esac 
done

read opts first_key nkeys retmax
opts=$(sed 's/db=/fromdb=/' <<< $opts)

base="http://eutils.ncbi.nlm.nih.gov/entrez/eutils/elink.fcgi"
opts="$opts&db=$dbto&usehistory=y"

echo $opts > /dev/stderr

for k in `seq $first_key $nkeys`; do
    out=$(wget -qO /dev/stdout "$base?$opts&query_key=$k&cmd=neighbor_history" | 
          xmlstarlet sel -t -m '/eLinkResult/LinkSet' \
                            -v 'WebEnv' -n \
                            -v 'LinkSetDbHistory/QueryKey')
    webenv=$(echo $out | awk '{print $1}')
    query_key=$(echo $out | awk '{print $2}')
done

echo "db=$dbto&WebEnv=$webenv $(( $nkeys + 1 )) $query_key $retmax"
